commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("new", views.new, name="new"),
    path("random", views.random, name="random"),
    path("edit/<str:search>", views.edit, name="edit"),
    path("<str:search>", views.entry, name="entry")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django import forms
from markdown2 import Markdown
from random import randint

from . import util

markdowner = Markdown()

# create new class for query form
class NewQueryForm(forms.Form):
    query = forms.CharField(label="Search wiki")

# create new class for title form
class NewTitleForm(forms.Form):
    title = forms.CharField(label="Enter page title")

# define index view
def index(request):
    # post method covers the search functionality on the home page
    if request.method == "POST":
        form = NewQueryForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data["query"]
            entries = util.list_entries()
            # if exact match found, return entry page
            if query in entries:
                return redirect('wiki:entry', query)
            # otherwise return list with links to matching pages
            else:
                matches = []
                for entry in entries:
                    if query in entry:
                        matches.append(entry)
                return render(request, "encyclopedia/search.html", {
                    "matches": matches,
                    "query": query
                })
    # if method is GET then simply return list of available entries
    else:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries(),
            "form": NewQueryForm()
        })

# define view to return entry page
def entry(request, search):
    # return error page of entry not found in wiki
    if util.get_entry(search) == None:
        return render(request, "encyclopedia/error.html")
    # otherwise convert Md file content to HTML and render entry page
    else:
        entry = markdowner.convert(util.get_entry(search))
        return render(request, "encyclopedia/entry.html", {
            "entry": entry,
            "search": search
    })

# define view for new entry page
def new(request):
    # post method if user submits new page
    if request.method == "POST":
        # submit new page
        titleform = NewTitleForm(request.POST)
        if titleform.is_valid():
            title = titleform.cleaned_data["title"]
            entries = util.list_entries()
            # return error response if wiki page already exists
            if title in entries:
                return HttpResponse(f"Error: A wiki page for {title} already exists.")
            content = request.POST['newpage']
            # if title check is passed then save Md file and return new page
            util.save_entry(title, content)
            return redirect('wiki:entry', title)
    # otherwise just render new entry page
    else:
        return render(request, "encyclopedia/new.html", {
            "titleform": NewTitleForm()
        })

# define view for edit entry page
def edit(request, search):
    # if user submits changes
    if request.method == "POST":
        # get title and content from request data
        search = request.POST["title"]
        content = request.POST["editpage"]
        # save the entry in place of existing and redirect to new page
        util.save_entry(search, content)
        return redirect('wiki:entry', search)
    # if user arrives from 'Edit Entry' link on entry page
    else:
        # get the entry content for respective entry title, render edit page with title/content
        content = util.get_entry(search)
        return render(request, "encyclopedia/edit.html", {
            "search": search,
            "content": content
        })

# define view for random page
def random(request):
    # generate random number between 0 and number of entires minus 1
    entries = util.list_entries()
    rand = randint(0, len(entries) - 1)
    # find random entry and redirect
    entry = entries[rand]
    return redirect('wiki:entry', entry)

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}

    <h1>Edit wiki page</h1>

    <form action="{% url 'wiki:edit' search %}" method="post">
        {% csrf_token %}
        <div>
            <label for="title">Title of wiki entry: </label>
        </div>

        <div>
            <input type="text" name="title" value="{{ search }}">
        </div>

        <div>
            <label for="editpage">Edit the wiki entry below:</label>
        </div>

        <div>
            <textarea id="editpage" name="editpage" placeholder="{{ content }}" rows="4" cols="50">{{ content|safe }}</textarea>
        </div>

        <div>
            <input class="page" type="submit" value="Save Changes">
        </div>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ search }}
{% endblock %}

{% block body %}

    {{ entry|safe }}

    <div class="edit">
        <p><a href="{% url 'wiki:edit' search %}">Edit Entry</a></p>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}

    <h1>Error!</h1>
    <p>The page you requested does not exist.</p>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:index' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}

    <h1>New wiki page</h1>

    <form action="{% url 'wiki:new' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="newpage">Create your custom wiki page by filling out the fields below:</label>
        </div>

        <div>
            {{ titleform }}
        </div>

        <div>
            <textarea id="newpage" name="newpage" rows="4" cols="50"> Add the Markdown content for your new wiki page here.</textarea>
        </div>

        <div>
            <input class="newpage" type="submit" value="Add New Page">
        </div>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}

    <h1>Search results for '{{ query }}':</h1>

    {% for match in matches %}

        <ul>
            <li><a href="/{{ match }}">{{ match }}</a></li>
        </ul>

    {% empty %}

        <p>No matches found.</p>

    {% endfor %}

{% endblock %}